# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

annotations:
  category: Fnb
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.0.0
dependencies:
  
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Fnb description
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/%%IMAGE_NAME%%/img/%%IMAGE_NAME%%-stack-220x234.png
keywords:
  - Fnb
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: fnb-cms
sources:
  - https://github.com/bitnami/containers/tree/main/tiktuzki/fnb-cms
  - %%UPSTREAM_PROJECT_SOURCE_CODE_URL%%
  - ...
version: 0.1.0
