{{- if and .Values.persistence.enabled ( .Values.persistence.create.enabled ) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "rd.fullname" . }}
  namespace: {{ include "rd.names.namespace" . | quote }}
  labels:
    {{- include "rd.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.create.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.create.size | quote }}
{{- if .Values.persistence.create.storageClass }}
{{- if (eq "-" .Values.persistence.create.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.create.storageClass }}"
{{- end }}
{{- end }}
{{- end }}