apiVersion: v1
kind: Service
metadata:
  name: {{ include "rd.fullname" . }}
  namespace: {{ include "rd.names.namespace" . | quote }}
  labels:
    {{- include "rd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports: {{- include "rd.service.ports" . | nindent 4 }} 
  selector:
    {{- include "rd.selectorLabels" . | nindent 4 }}
